lib/asciinema_web/router.ex
defmodule AsciinemaWeb.Router do
  use AsciinemaWeb, :router
  use Plug.ErrorHandler
  defp handle_errors(_conn, %{reason: %Phoenix.NotAcceptableError{}}), do: nil
  use Sentry.Plug
  import AsciinemaWeb.Auth, only: [require_current_user: 2, require_admin: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AsciinemaWeb.Auth
  end

  pipeline :asciicast do
    plug AsciinemaWeb.TrailingFormat
    plug :accepts, ["html", "js", "json", "cast", "svg", "png", "gif"]
    plug :format_specific_plugs
    plug :put_secure_browser_headers
  end

  defp format_specific_plugs(conn, []) do
    format_specific_plugs(conn, Phoenix.Controller.get_format(conn))
  end

  defp format_specific_plugs(conn, "html") do
    conn
    |> fetch_session([])
    |> fetch_flash([])
    |> protect_from_forgery([])
    |> AsciinemaWeb.Auth.call([])
  end

  defp format_specific_plugs(conn, _other), do: conn

  pipeline :oembed do
    plug :accepts, ["json", "xml"]
    plug :put_secure_browser_headers
  end

  scope "/", AsciinemaWeb do
    pipe_through :asciicast

    resources "/a", AsciicastController, only: [:show, :edit, :update, :delete]
  end

  scope "/", AsciinemaWeb do
    pipe_through :oembed

    get "/oembed", OembedController, :show
  end

  scope "/", AsciinemaWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :show

    get "/explore", AsciicastController, :index
    get "/explore/:category", AsciicastController, :category

    get "/a/:id/iframe", AsciicastController, :iframe
    get "/a/:id/embed", AsciicastController, :embed
    get "/a/:id/example", AsciicastController, :example

    get "/docs", DocController, :index
    get "/docs/:topic", DocController, :show

    resources "/login", LoginController, only: [:new, :create], singleton: true
    get "/login/sent", LoginController, :sent, as: :login

    resources "/user", UserController, as: :user, only: [:edit, :update], singleton: true
    resources "/users", UserController, as: :users, only: [:new, :create]
    get "/u/:id", UserController, :show
    get "/~:username", UserController, :show

    resources "/username", UsernameController, only: [:new, :create], singleton: true
    get "/username/skip", UsernameController, :skip, as: :username

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    get "/connect/:api_token", ApiTokenController, :show, as: :connect

    resources "/api_tokens", ApiTokenController, only: [:delete]

    get "/about", PageController, :about
    get "/privacy", PageController, :privacy
    get "/tos", PageController, :tos
    get "/contact", PageController, :contact
    get "/contributing", PageController, :contributing
  end

  scope "/api", AsciinemaWeb.Api, as: :api do
    post "/asciicasts", AsciicastController, :create
  end

  pipeline :exq do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug AsciinemaWeb.Auth
    plug :require_current_user
    plug :require_admin
    plug ExqUi.RouterPlug, namespace: "admin/exq"
  end

  scope "/admin/exq", ExqUi do
    pipe_through :exq
    forward "/", RouterPlug.Router, :index
  end
end

defmodule AsciinemaWeb.Router.Helpers.Extra do
  alias AsciinemaWeb.Router.Helpers, as: H
  alias AsciinemaWeb.Endpoint

  def profile_path(_conn, user) do
    profile_path(user)
  end

  def profile_path(%Plug.Conn{} = conn) do
    profile_path(conn.assigns.current_user)
  end

  def profile_path(%{id: id, username: username}) do
    if username do
      "/~#{username}"
    else
      "/u/#{id}"
    end
  end

  def profile_url(user) do
    Endpoint.url() <> profile_path(user)
  end

  def asciicast_file_path(conn, asciicast) do
    H.asciicast_path(conn, :show, asciicast) <> "." <> ext(asciicast)
  end

  def asciicast_file_url(asciicast) do
    asciicast_file_url(AsciinemaWeb.Endpoint, asciicast)
  end

  def asciicast_file_url(conn, asciicast) do
    H.asciicast_url(conn, :show, asciicast) <> "." <> ext(asciicast)
  end

  defp ext(asciicast) do
    case asciicast.version do
      0 -> "json"
      1 -> "json"
      _ -> "cast"
    end
  end
end

lib/asciinema_web/views/layout_view.ex
defmodule AsciinemaWeb.LayoutView do
  use AsciinemaWeb, :view
  import AsciinemaWeb.UserView, only: [avatar_url: 1]

  def page_title(conn) do
    case conn.assigns[:page_title] do
      nil -> "asciinema - Record and share your terminal sessions, the right way"
      title -> title <> " - asciinema"
    end
  end

  def body_class(conn) do
    action = Phoenix.Controller.action_name(conn)

    controller =
      conn
      |> Phoenix.Controller.controller_module
      |> Atom.to_string
      |> String.replace(~r/(Elixir\.AsciinemaWeb\.)|(Controller)/, "")
      |> String.replace(".", "")
      |> Inflex.underscore
      |> String.replace("_", " ")
      |> Inflex.parameterize

    "c-#{controller} a-#{action}"
  end

  def main_class(conn) do
    conn.assigns[:main_class] || "container"
  end
end

lib/asciinema_web/templates/layout/_flash.html.eex
<%= if message = get_flash(@conn, :info) do %>
  <section class="flash notice"><div class="container"><%= message %></div></section>
<% end %>

<%= if message = get_flash(@conn, :error) do %>
  <section class="flash alert"><div class="container"><%= message %></div></section>
<% end %>

lib/asciinema_web/templates/layout/_footer.html.eex
<!-- app2 layout's footer -->

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-12">
        <ul class="links">
          <li><a href="/contributing">Contributing</a></li>
          <li><a href="/tos">Terms of Service</a></li>
          <li><a href="/privacy">Privacy Policy</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>

      <div class="col-md-4 col-xs-12 text-center">
        <span>
          Sponsored by
          <br/>
          <a class="brightbox-logo" href="http://brightbox.com/" rel="nofollow">
            <img src="<%= Routes.static_path(@conn, "/images/brightbox.png") %>" />
          </a>
        </span>
      </div>

      <div class="col-md-4 col-xs-12">
        <ul class="links float-right">
          <li>
            <b>forum:</b> <a href="https://discourse.asciinema.org">discourse.asciinema.org</a>
          </li>
          <li>
            <b>irc:</b> <a href="https://kiwiirc.com/nextclient/irc.freenode.net/#asciinema">#asciinema on freenode</a>
          </li>
          <li>
              <b>matrix:</b> <a href="https://matrix.to/#/#asciinema:matrix.org">#asciinema:matrix.org</a>
          </li>

          <li>
            <b>twitter:</b> <a href="https://twitter.com/asciinema" title="Follow @asciinema on Twitter">@asciinema</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/asciinema_web/templates/layout/_header.html.eex
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="<%= Routes.static_path(@conn, "/images/logo-red.svg") %>">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/explore">Watch</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= Routes.doc_path(@conn, :show, :"getting-started") %>">Record</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= Routes.doc_path(@conn, :show, :"how-it-works") %>">Docs</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="http://blog.asciinema.org">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
        </ul>

        <ul class="navbar-nav navbar-right session-info">
          <%= if @current_user do %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">

                <img class="avatar" src="<%= avatar_url(@current_user) %>"><%= @current_user.username || @current_user.email %>
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="<%= profile_path(@current_user) %>">Profile</a>
                <a class="dropdown-item" href="/user/edit">Settings</a>
                <%= link "Log out", to: Routes.session_path(@conn, :delete), class: "dropdown-item logout", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/login/new" id="log-in">Log in / Sign up</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

lib/asciinema_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title @conn %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <!-- google analytics -->
    <!-- content for head (twitter, open graph tags) -->
  </head>

  <body>
    <%= render "header.html", conn: @conn, current_user: @current_user %>
    <%= render "flash.html", conn: @conn %>

    <div class="main">
      <%= render @view_module, @view_template, assigns %>
    </div>

    <%= render "footer.html", conn: @conn %>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/asciinema_web/templates/layout/app2.html.eex
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title><%= page_title @conn %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app2.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <%= render_existing @view_module, "meta." <> @view_template, assigns %>
  </head>

  <body class="l-app <%= body_class(@conn) %>">
    <%= render "_header.html", conn: @conn, current_user: @current_user %>
    <%= render "_flash.html", conn: @conn %>

    <main role="main" class="<%= main_class(@conn) %>">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <%= render "_footer.html", conn: @conn %>

    <script src="<%= Routes.static_path(@conn, "/js/asciinema-player.js") %>"></script>
    <script src="<%= Routes.static_path(@conn, "/js/app2.js") %>"></script>
  </body>
</html>

lib/asciinema_web/templates/layout/docs.html.eex
<%= render @view_module, "wrapper.html", Map.merge(assigns, %{layout: {AsciinemaWeb.LayoutView, "app.html"}, topic_template: @view_template}) %>

lib/asciinema_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/asciinema_web/templates/layout/embed.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/embed.css") %>">
  </head>

  <body class="iframe">
    <script src="<%= Routes.static_path(@conn, "/js/asciinema-player.js") %>"></script>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/asciinema_web/templates/layout/example.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
     body { margin: 20px }
     .content {
       background-color: #ddd;
       padding: 20px;
       width: 960px;
     }
     p { font-family: serif; font-size: 16px }
    </style>
  </head>

  <body>
    <div class="content">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>

lib/asciinema_web/templates/layout/flash.html.eex
<%= if message = get_flash(@conn, :info) do %>
  <section class="flash notice"><div class="container"><%= message %></div></section>
<% end %>

<%= if message = get_flash(@conn, :error) do %>
  <section class="flash alert"><div class="container"><%= message %></div></section>
<% end %>

lib/asciinema_web/templates/layout/footer.html.eex
<!-- app1 layout's footer -->

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-4">
        <ul class="links">
          <li><a href="/contributing">Contributing</a></li>
          <li><a href="/tos">Terms of Service</a></li>
          <li><a href="/privacy">Privacy Policy</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>

      <div class="col-md-4 col-xs-4 text-center">
        <span>
          Sponsored by
          <br/>
          <a class="brightbox-logo" href="http://brightbox.com/" rel="nofollow">
            <img src="<%= Routes.static_path(@conn, "/images/brightbox.png") %>" />
          </a>
        </span>
      </div>

      <div class="col-md-4 col-xs-4">
        <ul class="links pull-right">
          <li>
            <b>forum:</b> <a href="https://discourse.asciinema.org">discourse.asciinema.org</a>
          </li>
          <li>
            <b>irc:</b> <a href="https://kiwiirc.com/nextclient/irc.freenode.net/#asciinema">#asciinema on freenode</a>
          </li>
          <li>
              <b>matrix:</b> <a href="https://matrix.to/#/#asciinema:matrix.org">#asciinema:matrix.org</a>
          </li>

          <li>
            <b>twitter:</b> <a href="https://twitter.com/asciinema" title="Follow @asciinema on Twitter">@asciinema</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/asciinema_web/templates/layout/header.html.eex
<header class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">
        <img src="<%= Routes.static_path(@conn, "/images/logo-red.svg") %>">
      </a>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/explore">Watch</a></li>
        <li><a href="<%= Routes.doc_path(@conn, :show, :"getting-started") %>">Record</a></li>
        <li><a href="<%= Routes.doc_path(@conn, :show, :"how-it-works") %>">Docs</a></li>
        <li><a href="http://blog.asciinema.org">Blog</a></li>
        <li><a href="/about">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right session-info">
        <%= if @current_user do %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <img class="avatar" src="<%= avatar_url(@current_user) %>"><%= @current_user.username || @current_user.email %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= profile_path(@current_user) %>">Profile</a></li>
              <li><a href="/user/edit">Settings</a></li>
              <li><%= link "Log out", to: Routes.session_path(@conn, :delete), class: "logout", method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/login/new" id="log-in">Log in / Sign up</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

lib/asciinema_web/templates/layout/iframe.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/iframe.css") %>">
  </head>

  <body class="iframe">
    <script src="<%= Routes.static_path(@conn, "/js/asciinema-player.js") %>"></script>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/asciinema_web/templates/layout/simple.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= page_title @conn %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <!-- google analytics -->
    <!-- content for head (twitter, open graph tags) -->
  </head>

  <body class="simple-layout">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>
  </body>
</html>