lib/asciinema_web/router.ex
defmodule AsciinemaWeb.Router do
  use AsciinemaWeb, :router
  use Plug.ErrorHandler
  defp handle_errors(_conn, %{reason: %Phoenix.NotAcceptableError{}}), do: nil
  use Sentry.Plug
  import AsciinemaWeb.Auth, only: [require_current_user: 2, require_admin: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AsciinemaWeb.Auth
  end

  pipeline :asciicast do
    plug AsciinemaWeb.TrailingFormat
    plug :accepts, ["html", "js", "json", "cast", "svg", "png", "gif"]
    plug :format_specific_plugs
    plug :put_secure_browser_headers
  end

  defp format_specific_plugs(conn, []) do
    format_specific_plugs(conn, Phoenix.Controller.get_format(conn))
  end

  defp format_specific_plugs(conn, "html") do
    conn
    |> fetch_session([])
    |> fetch_flash([])
    |> protect_from_forgery([])
    |> AsciinemaWeb.Auth.call([])
  end

  defp format_specific_plugs(conn, _other), do: conn

  pipeline :oembed do
    plug :accepts, ["json", "xml"]
    plug :put_secure_browser_headers
  end

  scope "/", AsciinemaWeb do
    pipe_through :asciicast

    resources "/a", AsciicastController, only: [:show, :edit, :update, :delete]
  end

  scope "/", AsciinemaWeb do
    pipe_through :oembed

    get "/oembed", OembedController, :show
  end

  scope "/", AsciinemaWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :show

    get "/explore", AsciicastController, :index
    get "/explore/:category", AsciicastController, :category

    get "/a/:id/iframe", AsciicastController, :iframe
    get "/a/:id/embed", AsciicastController, :embed
    get "/a/:id/example", AsciicastController, :example

    get "/docs", DocController, :index
    get "/docs/:topic", DocController, :show

    resources "/login", LoginController, only: [:new, :create], singleton: true
    get "/login/sent", LoginController, :sent, as: :login

    resources "/user", UserController, as: :user, only: [:edit, :update], singleton: true
    resources "/users", UserController, as: :users, only: [:new, :create]
    get "/u/:id", UserController, :show
    get "/~:username", UserController, :show

    resources "/username", UsernameController, only: [:new, :create], singleton: true
    get "/username/skip", UsernameController, :skip, as: :username

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    get "/connect/:api_token", ApiTokenController, :show, as: :connect

    resources "/api_tokens", ApiTokenController, only: [:delete]

    get "/about", PageController, :about
    get "/privacy", PageController, :privacy
    get "/tos", PageController, :tos
    get "/contact", PageController, :contact
    get "/contributing", PageController, :contributing
  end

  scope "/api", AsciinemaWeb.Api, as: :api do
    post "/asciicasts", AsciicastController, :create
  end

  pipeline :exq do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug AsciinemaWeb.Auth
    plug :require_current_user
    plug :require_admin
    plug ExqUi.RouterPlug, namespace: "admin/exq"
  end

  scope "/admin/exq", ExqUi do
    pipe_through :exq
    forward "/", RouterPlug.Router, :index
  end
end

defmodule AsciinemaWeb.Router.Helpers.Extra do
  alias AsciinemaWeb.Router.Helpers, as: H
  alias AsciinemaWeb.Endpoint

  def profile_path(_conn, user) do
    profile_path(user)
  end

  def profile_path(%Plug.Conn{} = conn) do
    profile_path(conn.assigns.current_user)
  end

  def profile_path(%{id: id, username: username}) do
    if username do
      "/~#{username}"
    else
      "/u/#{id}"
    end
  end

  def profile_url(user) do
    Endpoint.url() <> profile_path(user)
  end

  def asciicast_file_path(conn, asciicast) do
    H.asciicast_path(conn, :show, asciicast) <> "." <> ext(asciicast)
  end

  def asciicast_file_url(asciicast) do
    asciicast_file_url(AsciinemaWeb.Endpoint, asciicast)
  end

  def asciicast_file_url(conn, asciicast) do
    H.asciicast_url(conn, :show, asciicast) <> "." <> ext(asciicast)
  end

  defp ext(asciicast) do
    case asciicast.version do
      0 -> "json"
      1 -> "json"
      _ -> "cast"
    end
  end
end

lib/asciinema/accounts/user.ex
defmodule Asciinema.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Asciinema.Accounts.User

  @valid_email_re ~r/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i
  @valid_username_re ~r/^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$/
  @valid_theme_names ["asciinema", "tango", "solarized-dark", "solarized-light", "monokai"]

  @timestamps_opts [type: :utc_datetime_usec]

  schema "users" do
    field :username, :string
    field :temporary_username, :string
    field :email, :string
    field :name, :string
    field :auth_token, :string
    field :theme_name, :string
    field :asciicasts_private_by_default, :boolean, default: true
    field :last_login_at, :utc_datetime_usec
    field :is_admin, :boolean

    timestamps(inserted_at: :created_at)

    has_many :asciicasts, Asciinema.Asciicasts.Asciicast
    has_many :api_tokens, Asciinema.Accounts.ApiToken
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :name, :username, :theme_name, :asciicasts_private_by_default])
    |> validate_format(:email, @valid_email_re)
    |> validate_format(:username, @valid_username_re)
    |> validate_length(:username, min: 2, max: 16)
    |> validate_inclusion(:theme_name, @valid_theme_names)
    |> unique_constraints
  end

  def create_changeset(struct, attrs) do
    struct
    |> changeset(attrs)
    |> generate_auth_token
  end

  def signup_changeset(attrs) do
    %User{}
    |> create_changeset(attrs)
    |> cast(attrs, [:email])
    |> validate_required([:email])
    |> unique_constraints
  end

  def update_changeset(%User{} = user, attrs) do
    user
    |> changeset(attrs)
    |> validate_required([:username, :email])
    |> unique_constraints
  end

  def unique_constraints(changeset) do
    changeset
    |> unique_constraint(:username, name: "index_users_on_username")
    |> unique_constraint(:email, name: "index_users_on_email")
  end

  def login_changeset(user) do
    change(user, %{last_login_at: Timex.now()})
  end

  def temporary_changeset(temporary_username) do
    %User{}
    |> change(%{temporary_username: temporary_username})
    |> generate_auth_token
  end

  defp generate_auth_token(changeset) do
    put_change(changeset, :auth_token, Crypto.random_token(20))
  end
end

lib/asciinema_web/controllers/user_controller.ex
defmodule AsciinemaWeb.UserController do
  use AsciinemaWeb, :controller
  alias Asciinema.Accounts
  alias Asciinema.Authorization, as: Authz
  alias Asciinema.Asciicasts
  alias AsciinemaWeb.Auth

  plug :require_current_user when action in [:edit, :update]

  def new(conn, %{"t" => signup_token}) do
    conn
    |> put_session(:signup_token, signup_token)
    |> redirect(to: Routes.users_path(conn, :new))
  end

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, _params) do
    signup_token = get_session(conn, :signup_token)
    conn = delete_session(conn, :signup_token)

    case Accounts.verify_signup_token(signup_token) do
      {:ok, user} ->
        conn
        |> Auth.log_in(user)
        |> put_flash(:info, "Welcome to asciinema!")
        |> redirect(to: "/username/new")

      {:error, :token_invalid} ->
        conn
        |> put_flash(:error, "Invalid sign-up link.")
        |> redirect(to: Routes.login_path(conn, :new))

      {:error, :token_expired} ->
        conn
        |> put_flash(:error, "This sign-up link has expired, sorry.")
        |> redirect(to: Routes.login_path(conn, :new))

      {:error, :email_taken} ->
        conn
        |> put_flash(:error, "You already signed up with this email.")
        |> redirect(to: Routes.login_path(conn, :new))
    end
  end

  def show(conn, params) do
    with {:ok, user} <- fetch_user(params) do
      do_show(conn, params, user)
    end
  end

  defp do_show(conn, params, user) do
    current_user = conn.assigns.current_user
    user_is_self = !!(current_user && (current_user.id == user.id))

    filter =
      case user_is_self do
        true -> :all
        false -> :public
      end

    page =
      Asciicasts.paginate_asciicasts(
        {user.id, filter},
        :date,
        params["page"],
        15
      )

    conn
    |> put_layout(:app2)
    |> assign(:page_title, "#{user.username}'s profile")
    |> assign(:main_class, "")
    |> render(
      "show.html",
      user: user,
      user_is_self: user_is_self,
      asciicast_count: page.total_entries,
      page: page,
      show_edit_link: Authz.can?(current_user, :update, user)
    )
  end

  defp fetch_user(%{"id" => id}) do
    case Integer.parse(id) do
      {id, ""} -> Accounts.fetch_user(id)
      _ -> {:error, :not_found}
    end
  end

  defp fetch_user(%{"username" => username}) do
    Accounts.fetch_user(username: username)
  end

  def edit(conn, _params) do
    user = conn.assigns.current_user
    changeset = Accounts.change_user(user)
    render_edit_form(conn, user, changeset)
  end

  def update(conn, %{"user" => user_params}) do
    user = conn.assigns.current_user

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Account settings saved.")
        |> redirect(to: profile_path(conn, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render_edit_form(conn, user, changeset)
    end
  end

  defp render_edit_form(conn, user, changeset) do
    api_tokens = Accounts.list_api_tokens(user)

    render(conn, "edit.html",
      changeset: changeset,
      api_tokens: api_tokens)
  end
end

lib/asciinema_web/views/user_view.ex
defmodule AsciinemaWeb.UserView do
  use AsciinemaWeb, :view
  import Scrivener.HTML
  alias Asciinema.Gravatar

  def avatar_url(user) do
    username = username(user)
    email = user.email || "#{username}+#{user.id}@asciinema.org"
    Gravatar.gravatar_url(email)
  end

  def username(user) do
    user.username || user.temporary_username || "user:#{user.id}"
  end

  def display_name(user) do
    if String.trim("#{user.name}") != "" do
      user.name
    end
  end

  def joined_at(user) do
    Timex.format!(user.created_at, "{Mfull} {D}, {YYYY}")
  end

  def theme_name(user) do
    user.theme_name
  end

  def theme_options do
    [
      {"asciinema", "asciinema"},
      {"Tango", "tango"},
      {"Solarized Dark", "solarized-dark"},
      {"Solarized Light", "solarized-light"},
      {"Monokai", "monokai"},
    ]
  end

  def active_tokens(api_tokens) do
    api_tokens
    |> Enum.reject(&(&1.revoked_at))
    |> Enum.sort_by(&(- Timex.to_unix(&1.created_at)))
  end

  def revoked_tokens(api_tokens) do
    api_tokens
    |> Enum.filter(&(&1.revoked_at))
    |> Enum.sort_by(&(- Timex.to_unix(&1.created_at)))
  end
end

lib/asciinema_web/templates/user/edit.html.eex
<div class="container edit-page">
  <div class="row">
    <div class="col-md-9">
      <%= form_for @changeset, Routes.user_path(@conn, :update), [class: "simple_form form-horizontal", novalidate: "novalidate", role: "form"], fn f -> %>
        <legend>Account settings</legend>

        <div class="form-group string optional user_username <%= error_class(f, :username) %>">
          <%= label f, :username, class: "string optional control-label col-sm-3 col-md-3 col-lg-2 control-label" %>
          <div class="col-sm-9 col-md-9 col-lg-10">
            <%= text_input f, :username, class: "string optional form-control" %>
            <%= error_tag f, :username %>
          </div>
        </div>

        <div class="form-group email required user_email <%= error_class(f, :email) %>">
          <%= label f, :email, class: "email required control-label col-sm-3 col-md-3 col-lg-2 control-label" %>
          <div class="col-sm-9 col-md-9 col-lg-10">
            <%= email_input f, :email, class: "string email required form-control" %>
            <%= error_tag f, :email %>
          </div>
        </div>

        <div class="form-group string optional user_name <%= error_class(f, :name) %>">
          <%= label f, :name, "Full name", class: "string optional control-label col-sm-3 col-md-3 col-lg-2 control-label" %>
          <div class="col-sm-9 col-md-9 col-lg-10">
            <%= text_input f, :name, class: "string optional form-control" %>
            <%= error_tag f, :name %>
          </div>
        </div>

        <div class="form-group select optional user_theme_name">
          <%= label f, :theme_name, "Terminal theme", class: "select optional control-label col-sm-3 col-md-3 col-lg-2 control-label" %>
          <div class="col-sm-9 col-md-9 col-lg-10">
            <%= select f, :theme_name, theme_options(), class: "select optional form-control", prompt: "Default (asciinema)" %>
            <p class="help-block">Applies to all your asciicasts unless custom theme chosen for a specific asciicast</p>
          </div>
        </div>

        <div class="form-group radio_buttons optional user_asciicasts_private_by_default">
          <%= label f, :asciicasts_private_by_default, "Asciicast visibility", class: "radio_buttons optional control-label col-sm-3 col-md-3 col-lg-2 control-label" %>
          <div class="col-sm-9 col-md-9 col-lg-10">
            <label class="radio">
              <%= radio_button f, :asciicasts_private_by_default, false, class: "radio_buttons optional" %>public
            </label>
            <label class="radio">
              <%= radio_button f, :asciicasts_private_by_default, true, class: "radio_buttons optional" %>private
            </label>
            <p class="help-block">Applies to all *new* asciicasts</p>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9 col-md-offset-3 col-md-9 col-lg-offset-2 col-lg-10">
            <%= submit "Save", class: "btn btn-primary" %>
            <%= link "Cancel", to: profile_path(@conn), class: "btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <legend>Recorder tokens</legend>

      <%= if present?(@api_tokens) do %>
        <p>
          The following recorder tokens have been associated with your account:
        </p>

        <ul>
          <%= for t <- active_tokens(@api_tokens) do %>
            <li><code><%= t.token %></code> registered <%= time_tag(t.created_at) %> - <%= link "Revoke", to: Routes.api_token_path(@conn, :delete, t), method: "delete", data: [confirm: "Are you sure?"] %></li>
          <% end %>
        </ul>

        <ul>
          <%= for t <- revoked_tokens(@api_tokens) do %>
            <li class="revoked-token"><code><%= t.token %></code> registered <%= time_ago_tag(t.created_at) %>, revoked <%= time_ago_tag(t.revoked_at) %>
          <% end %>
        </ul>
      <% else %>
        <p>
          If you want your recordings to be assigned to your profile
          you have to register your local recorder token.
        </p>

        <p>
          There is currently no recorder token associated with your account.
          Run <code>asciinema auth</code> in your terminal to register one.
        </p>
      <% end %>
    </div>
  </div>
</div>

lib/asciinema_web/templates/user/new.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Verifying link...</h1>
    </div>
  </div>
</div>

<%= form_for @conn, Routes.users_path(@conn, :create), [id: "login", as: :login], fn _f -> %>
<% end %>

<script>
  document.forms.namedItem("login").submit();
</script>

lib/asciinema_web/templates/user/show.html.eex
<div class="profile-page">
  <section class="cinema">
    <div class="container">
      <span class="user-avatar">
        <%= img_tag avatar_url(@user), class: "avatar" %>
      </span>

      <h1>
        <%= if name = display_name(@user) do %>
          <%= name %> (<%= username(@user) %>)
        <% else %>
          <%= username(@user) %>
        <% end %>

        <small>Joined on <%= joined_at(@user) %></small>
      </h1>

      <%= if @show_edit_link do %>
        <p class="actions">
          <%= link "Edit profile", to: Routes.user_path(@conn, :edit) %>
        </p>
      <% end %>
    </div>
  </section>

  <div class="container">
    <%= if @user_is_self do %>
      <%= if @asciicast_count > 0 do %>
        <h2>You have recorded <%= pluralize(@asciicast_count, "asciicast") %></h2>
      <% else %>
        <h2>Record your first asciicast</h2>
      <% end %>
    <% else %>
      <%= if @asciicast_count > 0 do %>
        <h2><%= pluralize(@asciicast_count, "public asciicast") %> by <%= username(@user) %></h2>
      <% else %>
        <h2><%= username(@user) %> has no public asciicasts</h2>
      <% end %>
    <% end %>

    <div class="row asciicast-list">
      <div class="col-md-12">
        <%= case {@asciicast_count, @user_is_self} do %>
        <% {0, true} -> %>
          <p>
            Make sure you have asciinema recorder <%= link "installed", to: Routes.doc_path(@conn, :show, :installation) %>.
          </p>

          <p>
            To start recording run the following command in your terminal:
          </p>

          <pre><code>$ asciinema rec</code></pre>

          <p>
            When you're ready to finish just exit the shell,
            either by typing <code>exit</code> or hitting <kbd>C-d</kbd>.
          </p>

          <p>
            If you have already recorded an asciicast but you don't see it
            here then associate it with your account by running
            <code>asciinema auth</code> in your terminal.
          </p>

        <% {0, false} -> %>

        <% _ -> %>
          <%= for asciicasts <- Enum.chunk_every(@page, 3, 3) do %>
            <div class="row">
              <%= for asciicast <- asciicasts do %>
                <div class="col-md-4">
                  <%= render AsciinemaWeb.AsciicastView, "_card.html", conn: @conn, asciicast: asciicast %>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <%= if @page.total_pages > 1 do %>
      <div class="row">
        <div class="col">
          <%= pagination_links @page %>
        </div>
      </div>
    <% end %>
  </div>
</div>